RPCHost = "localhost:10009"
InvoiceMacaroonPath = "/home/alice/.lnd/data/chain/bitcoin/mainnet/invoices.macaroon"
TLSCertPath = "/home/alice/.lnd/tls.cert"
WorkingDir = "/home/alice/.go-host-lnaddr"
ExternalURL = "https://allmysats.com"
ListAllURLs = true
MinSendableMsat = 1000
MaxSendableMsat = 100000000
MaxCommentLength = 150
Tag = "payRequest"
Thumbnail = "/path/to/thumbnail.[jpeg|png]"
SuccessMessage = "Thank you!"
InvoiceCallback = "https://allmysats.com/invoice/"
AddressServerPort = 9990

LightningAddresses = ["tips@allmysats.com"]

[[Metadata]]
type = "text/plain"
value = "Welcome to allmysats.com"

[[Metadata]]
type = "text/identifier"
value = "tips@allmysats.com"

[Nostr]
[Nostr.names]
myNostrUsername = "npub1h....."
[Nostr.relays]
b9b = ["wss://my.relay.com"]

[[Notificators]]
Type = "mail"
MinAmount = 1000
[Notificators.Params]
From = "tips@allmysats.com"
Target = "username@example.com"
SmtpServer = "smtp.allmysats.com:587"
Login = "tips@allmysats.com"
Password = "somerandompassword"

[[Notificators]]
Type = "telegram"
MinAmount = 1000
[Notificators.Params]
ChatId = "1234567890"
Token = "TelegramToken"

[[Notificators]]
Type = "http"
MinAmount = 1000
[Notificators.Params]
Target = "https://example.com/notify?amount={{.Amount}}"
Method = "POST"
Encoding = "application/x-www-form-urlencoded"
BodyTemplate = "message={{.Message}}&title=New+payment+received"